version: '3.8'

services:
  bot-subscription:
    build: .
    container_name: bot-payment
    env_file:
      - .env
    environment:
      DB_NAME: /data/subscriptions.db
    volumes:
      - ./data:/data
    restart: unless-stopped
    mem_limit: 512m